#!/bin/bash/

clear

################################################################################################################
#Git branch in prompt and other bash goodies - see the section #MY OWN, there are two uncommented lines

parse_git_branch() {

	local gitdir=$(git rev-parse --git-dir 2>/dev/null)

	if [ $? -ne 0 ] || [ -z "$gitdir" ]; then
		return
	fi

	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'

}

git_parse_remote() {
# Still under construction

    git remote 2> /dev/null 

}

# BASH PROMPT WITH USEFUL INFO ONLY
RED="\[\033[0;31m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
WHITE="\[\033[00m\]"
export PS1="$YELLOW@\u $WHITE\w/ $GREEN\$(parse_git_branch) $WHITE\n$ "
export PS2="\$ "

# BASH CODE COMPLETION
# NOTE: not sure if this works...

if type brew 2&>/dev/null; then
  for completion_file in $(brew --prefix)/etc/bash_completion.d/*; do
    source "$completion_file"
  done
fi
################################################################################################################

# Other useful shortcuts for Bash
alias ll='ls -lahG'
alias Restart=". ~/.bash_profile"
alias t1="tree -L 1"
alias t2="tree -L 2"
alias t3="tree -L 3"

# Git specific aliases - use with care
alias gs="git status"
alias ga="git add"
alias gcm="git commit -m"
alias gp="git push"
alias gl="git log"
alias gpr="CURRENT_BRANCH=$`git rev-parse --abbrev-ref HEAD`; git push --set-upstream $1 $CURRENT_BRANCH"
alias ggg="ga . && gcm"


# Shortcuts to manage this file quickly
alias cb="cat ~/.bash_profile"
alias vb="vim ~/.bash_profile"
alias rb=". ~/.bash_profile"


alias bfg="java -jar bfg.jar"
alias vimrc="vim ~/.vimrc"


# Directory quickaccess shortcuts
alias laravel-tutorial="cd ~/PHP/tutorialpoint/–-prefer-dist/"
alias sites="cd ~/PHP/Sites"


# Path exports
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="~/Homestead:$PATH"

function homestead() {
    ( cd ~/Homestead && vagrant $* )
}

